# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish PyClinic to pypi

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: "The semver version number to bump to (ie: v1.2.3)"
        required: true
        default: "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Autobump version
        run: |
          echo "Finding version values..."
          # from refs/tags/v1.2.3 get 1.2.3
          VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
          PYPROJECT_VERSION=$(poetry run python ./scripts/pyproject.py)

          echo "Version found in pyproject.toml: $PYPROJECT_VERSION"

          # Set if VERSION was set by manually triggered workflow
          if [ ${{ github.event.inputs.version }} != "develop" ]; then
              VERSION=${{ github.event.inputs.version }}
          fi

          echo "Version found from GitHub: $VERSION"

          if [ "$VERSION" > "$PYPROJECT_VERSION" ]; then
              echo "$VERSION is valid. Setting it with poetry..."
              poetry version $VERSION
          else
              echo "$VERSION is invalid! It must be greater than $PYPROJECT_VERSION"
              exit 1
          fi
        shell: bash

      - name: Build and publish
        run: |
          poetry build
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_TOKEN }}
